flugg/laravel-responder

src/Http/SuccessResponseBuilder.php

Hello, I found the point where it breaks. When we feed response factory a custom built paginator it fails to resolve model out of the resource because we are manually slicing the collection and when we are on page 2 or 3 we simply don't have an item with `0` index in the array and it's failing to resolve a model. This is not the case when we do `->paginate()` on query builder because it's not slicing a collection, but it adds `limit` and `offset` on actual sql query so we always have 0 indexed element.

Get actual first item of an array rather than by 0 index when resolving model out of the resource 

---

src/Http/SuccessResponseBuilder.php

At the moment if you visit a url like `http://api.myapp.dev/?include=users,posts` it will try to load the `users,posts` relationship instead of `['users', 'posts']`.

Split relations to include

---

src/Exceptions/Http/ApiException.php

This change allows to set a message inside an exception so the error message doesn't have to be moved to the language file. _I don't know to any API that serves their error messages in multiple languages and this would keep all error related details in one place._
```php
<?php
namespace App\Exceptions;
use Flugg\Responder\Exceptions\Http\ApiException;
class AccessDeniedException extends ApiException
{
/**
* The HTTP status code.
*
* @var int
*/
protected $statusCode = 403;
/**
* The error code used for API responses.
*
* @var string
*/
protected $errorCode = 'access_denied';
/**
* The error message.
*
* @var string
*/
protected $message = 'Access Denied';
}
```

Add message property to ApiException

---

src/Serializers/ApiSerializer.php
tests/Integration/MakeSuccessResponseTest.php

This will include the links for the next/previous page returned from the Fractal Serializer which allow easy access to the next results

Include paginator links

---

src/ResourceFactory.php

Without this change `https://service.com/api/books?include=author` would return `https://service.com/api/books?page=2` as the next page instead of `https://service.com/api/books?include=author&page=2`.
See http://fractal.thephpleague.com/pagination/

Including existing query string values in pagination links

---

resources/config/responder.php
src/Responder.php

This PR adds support for error presets which consist of an identifier, error code, status code and message.
```php
'access_denied' => [
'errorCode'  => 'ERR-ACCESS-DENIED',
'statusCode' => 403,
'message'    => 'Access Denied',
],
'bad_gateway' => [
'errorCode'  => 'ERR-BAD-GATEWAY',
'statusCode' => 502,
'message'    => 'Bad Gateway',
],
'bad_request' => [
'errorCode'  => 'ERR-BAD-REQUEST',
'statusCode' => 400,
'message'    => 'Bad Request',
],
```
This allows for an easier, faster and cleaner way of returning errors and stops the continuous repetition of error codes and messages in controllers.
So instead of `return responder()->error('ERR-ACCESS-DENIED', 403, 'Access Denied');` we could then do `responder()->error('access_denied');`.

Add support for error presets

---

.gitignore
resources/config/responder.php
src/Http/ErrorResponseBuilder.php
src/Http/ResponseBuilder.php
src/Http/SuccessResponseBuilder.php
src/Responder.php
src/ResponderServiceProvider.php
src/Serializers/ApiSerializer.php
tests/TestCase.php
tests/Unit/ErrorResponseBuilderTest.php
tests/Unit/SuccessResponseBuilderTest.php

Looking to make the success property optional as it is redundant when validating a response from a client.

Make success property optional

---

src/Traits/HandlesApiErrors.php

Hi,
I have come across this when setting the Laravel `App\Exceptions\Handler` to use `Flugg\Responder\Exceptions\Handler as ExceptionHandler`. It looks like lines 78-80 of the file  `laravel-responder/src/Traits/HandlesApiErrors.php` catches and throws the same error. Should the newly thrown error be an instance of `Flugg\Responder\Exceptions\Http\RelationNotFoundException` instead of  `Illuminate\Database\Eloquent\RelationNotFoundException`

Throw the Responder RelationNotFoundException instead of the Eloquent version

---

README.md

Removed `transform` method on `SuccessResponseBuilder`, use `success` instead

Fix removed method example.

---

README.md

I would rather leave fix the parent class and change it to 'code' class variable...

Fix the example exception typo

---

composer.json

Allow the installation of the package on a fresh clone of [laravel/laravel](https://github.com/laravel/laravel/blob/master/composer.json#L16).

chore: Loosened mockery dependency.

---

src/ResponderServiceProvider.php

Removed interdependence between transformation requests (which all shared a TransformFactory reference) which led, when using transform helper inside a transformer 'transform()' method, into overwriting the SuccessSerializer with an unwanted NullSerializer. Unit test is not possible, testing is delegated to future Feature tests.
This resolves #86

Transformations now uses a new FractalTransformFactory for every request instead of sharing a singleton

---

README.md
src/TransformBuilder.php
tests/Unit/TransformBuilderTest.php

Now parameters are managed correctly, stripping them away from the relation name before loading it on the model but leaving them when relations are given to the underlying Fractal implementation.
This resolves #83.

Fractal parameters bugfix

---

composer.json
src/Contracts/TransformFactory.php
src/Contracts/Transformer.php
src/FractalTransformFactory.php
src/Serializers/NullSerializer.php
src/Serializers/SuccessSerializer.php
src/TransformBuilder.php
src/Transformer.php
src/helpers.php
tests/Unit/Serializers/NullSerializerTest.php
tests/Unit/Serializers/SuccessSerializerTest.php

This solves #82.
A Feature test suite is required to test this extensively.
**_May_** require to increment major version number given that null data, previously transformed as an empty array, is now returned as null as it should be.
I don't know for certain if this shall be considered as a bugfix (the array representation wasn't the intended behaviour in first place as I understood), a retro-compatible change or a breaking change.
I think it could be intended as a retro-compatible change, given that it bring with it also an update on the needed required PHP version (7.0 -> 7.1). The change can be done also avoiding to update the PHP version dependency if needed.

NullSerializer returns null for null values instead of empty array

---

README.md
src/Http/Responses/Decorators/EscapeHtmlDecorator.php

I think that this simple decorator can be a precious ally to prevent XSS attacks when the API consumer is a web-client which will print user generated data into a page.
It's based on "sanitize input, encode output" paradigm.
There are usually two scenarios here and I have in mind the "always use the safer default" idea.
The hypothesis is that we stored data into our database "as is", which is the way I usually prefer because I don't want to ruin data I collect.
We can return it "as is", in which case if the developer print it as HTML by mistake we'll have an XSS attack, or we can return it escaped, in which case if the developer prints it as text by mistake it will display as an ugly string.
I prefer the latter, hence I created this decorator.
If you think there is a more efficient way to …

EscapeHtmlDecorator

---

src/Exceptions/ConvertsExceptions.php

_I created an http error with custom header. But the header was not sent as a response. And I fixed it_

Fix bug do not send headers in response

---

src/ErrorMessageResolver.php
tests/Unit/ErrorMessageResolverTest.php

They removed trans() method from Translator class on Laravel 6.0, get() method should be used instead of it. It is also valid for previous releases.
https://github.com/laravel/framework/commit/8557dc56b11c5e4dc746cb5558d6e694131f0dd8#diff-aebbba80d9a2718c0fe6105c28bd4813

trans() method to get() for Laravel 6.0

---

src/Console/MakeTransformer.php
src/TransformBuilder.php
src/Transformers/Concerns/HasRelationships.php
src/Transformers/Concerns/MakesResources.php
tests/Feature/IncludeRelationTest.php
tests/Unit/TransformBuilderTest.php

array_ and str_ helpers are removed and transferred to laravel/helpers package. So these methods don't work on Laravel 6.0
I have converted them to current way recommended on Laravel documentation.
https://laravel.com/docs/6.0/upgrade#helpers

str and array helpers converted to support classes for Laravel 6.0

---

config/responder.php
src/TransformBuilder.php
src/Transformers/Concerns/HasRelationships.php
src/Transformers/Concerns/MakesResources.php
tests/Feature/IncludeRelationTest.php

i have existing project that use non camel case relation method, when using laravel responder which convert all relations to camelcase make it fail to work,, so i add config to enable/disable camel-case convert, by default is using camel-case, but if we want to disable it just set it on config:
use_camel_case_relations => false

add non camel-case relations support

---

composer.json

PHP version update and fzaninotto/faker reference removal. Tests run smoothly with php 8.0

PHP 8.0 support

---

src/Http/Middleware/ConvertToSnakeCase.php

Changed the reference in the SnakeCase middleware to use the updated Str::snake()

Remove usage of snake_case helper function

---

src/Contracts/ErrorFactory.php
src/Contracts/ErrorSerializer.php
src/Contracts/Resources/ResourceFactory.php
src/Contracts/Responder.php
src/Contracts/SimpleTransformer.php
src/ErrorFactory.php
src/Exceptions/Http/HttpException.php
src/Http/MakesResponses.php
src/Http/Responses/ErrorResponseBuilder.php
src/Http/Responses/ResponseBuilder.php
src/Http/Responses/SuccessResponseBuilder.php
src/Resources/ResourceFactory.php
src/Responder.php
src/Serializers/ErrorSerializer.php
src/Testing/MakesApiRequests.php
src/TransformBuilder.php
src/Transformation.php
src/Transformers/Concerns/MakesResources.php
tests/TestCase.php

Fix php8.4 deprecated warnings

fix php 8.4 Deprecated warnings

---

src/Exceptions/Http/UnauthorizedException.php

The HTTP standard clearly defines Unauthorized as 401. This change is intended to adhere to said standard.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

Change UnauthorizedException http code from 403 to 401
